def alltypes():
    types = {
    "Marine Fire On Water":["Marine","Fire"],
    "Tank Farm":["HazMat"],
    "Mutual Aid, Adv. Life":["Medical"],
    "Automatic Fire Fire Dist 11":["Fire"],
    "Medic Resp Infectious":["Medical"],
    "Automatic Fire Dist 11":["Fire"],
    "Mutual Aid, Strike Team En":["Rescue"],
    "Rescue Salt Water Maj":["Rescue"],
    "Monorail Fire on the beam":["Fire"],
    "Explosion Unk Situation":["Fire"],
    "Fire in a Highrise":["Fire"],
    "Automatic Aid Dist 11":["Fire"],
    "Med 7 Resp Infectious":["Medical"],
    "Mutual Aid Strike Team Lad":["Rescue"],
    "Mutual Aid Task Force Stru":["Rescue"],
    "Boat<50' on Water Fire/Res":["Fire","Marine"],
    "Rescue Standby Water":["Rescue","Marine"],
    "Mutual Aid  Basic Life":["Medical"],
    "Brush Fire Major":["Fire"],
    "W1RED - 1  Unit":["Medical"],
    "Haz Unk":["HazMat"],
    "Rescue Fresh Water Maj":["Marine","Rescue"],
    "WAFA4 - Auto Alarm 2+1+1":["Fire"],
    "Mutual Aid, Basic Life Sup":["Medical"],
    "Vessel Sinking On Shore":["Marine"],
    "Mutual Aid, Tech Res":["Rescue"],
    "Marine Fire On Shore":["Fire","Marine"],
    "Mutual Aid, Marine":["Marine"],
    "Marine Service Response":["Marine"],
    "Mutual Aid, Strike Team Lad":["Rescue"],
    "Aircraft Crash":["Aircraft"],
    "Tunnel Fire":["Fire"],
    "Natur Gas Leak Inside Comm":["HazMat"],
    "Rescue Water Major":["Rescue","Marine"],
    "Tanker Fire":["Fire"],
    "Rescue Ice":["Rescue"],
    "Natur Gas Leak Inside Comp":["HazMat"],
    "Tunnel Aid":["Medical"],
    "Aid Resp Infectious":["Medical"],
    "Aircraft Standby":["Aircraft"],
    "Explosion Major":["Fire","HazMat"],
    "Natur Gas Outside, Major":["HazMat"],
    "Mutual Aid, Hazmat":["HazMat"],
    "Hazardous Decon":["HazMat"],
    "Help the Fire Fighter":["Rescue"],
    "Ship Fire 50' on Water":["Marine","Fire"],
    "Tunnel Medic":["Medical"],
    "Natur Gas Leak Inside Res.":["HazMat"],
    "Marine Recon Response":["Marine"],
    "Water Rescue Recon Response":["Marine"],
    "Rescue Trench":["Rescue"],
    "Hazardous Material w/Fire":["HazMat","Fire"],
    "Fire House Boat":["Fire","Marine"],
    "Mutual Aid, Strike Eng.":["Rescue"],
    "AFAH - Auto Alarm Hazmat":["HazMat"],
    "Boat <50' Shr/Mar Fire/Res":["Marine"],
    "Boat Under 50' Unknown Sit":["Marine"],
    "Water Rescue Response":["Marine","Rescue"],
    "Rescue Heavy Major":["Rescue"],
    "Hazmat Unk":["HazMat"],
    "HazMat MCI":["HazMat"],
    "Boat Taking on Water Major":["Marine"],
    "Rescue Standby":["Rescue"],
    "Reduce Resp Opposite Tunnel":["Rescue"],
    "Rescue Confined Space":["Rescue"],
    "Mutual Aid, Task Force":["Rescue"],
    "COMED Poss Patient":["Medical"],
    "Rescue High Angle":["Rescue"],
    "Natur Gas Odor Inside Resident":["HazMat"],
    "Boat Under 50' Fire Water":["Fire","Marine"],
    "Boat Fire In Marina":["Fire","Marine"],
    "Boat Under 50' Unknown":["Marine"],
    "Pier Fire":["Marine"],
    "Mutual Aid, Ladder":["Rescue"],
    "Natur Gas Odor Commercial":["HazMat"],
    "Explosion Minor":["HazMat","Fire"],
    "Rescue Saltwater":["Rescue","Marine"],
    "Boat Under 50' Fire Shore":["Fire","Marine"],
    "Natural Gas Leak Major":["HazMat"],
    "Natur Gas Odor Outside":["HazMat"],
    "Shed Fire":["Fire"],
    "Fast Back Up":["Rescue"],
    "LINK - Link Control Center":["Rescue"],
    "Ship Fire 50'on Shore/Pier":["Fire","Marine"],
    "MUK9 - FIU CAPTAIN K9":["Rescue"],
    "Multiple Casualty Incident":["Medical"],
    "Vault Fire (Electrical)":["Fire"],
    "MVI Freeway Medic":["Medical","Vehicle"],
    "Mutual Aid, Aid":["Medical"],
    "RMC Chief":["Rescue"],
    "Drill":["Rescue"],
    "Motor Vehicle Incident Freeway":["Vehicle"],
    "Natur Gas Leak Outside Minor":["HazMat"],
    "Boat Taking Water Minr/Sho":["Marine"],
    "HAZADV - Hazmat Advised":["HazMat"],
    "Brush Fire Freeway":["Fire"],
    "Rescue Salt Water":["Rescue","Marine"],
    "Dumpster Fire W/Exp.":["Fire"],
    "Water Job Major":["Rescue"],
    "Garage Fire":["Fire"],
    "Brush Fire W/Exp.":["Fire"],
    "Multiple Medic Resp 14 Per":["Medical"],
    "Assault w/Weapons 14":["Medical"],
    "Spill, Non-Hazmat":["HazMat"],
    "Car Fire W/Exp.":["Fire","Vehicle"],
    "MVI Medic":["Medical","Vehicle"],
    "Mutual Aid, Engine":["Fire"],
    "Fire Response Freeway":["Vehicle","Fire"],
    "Aid Service":["Vehicle"],
    "Rescue Rope":["Rescue"],
    "Rescue Fresh Water":["Rescue","Marine"],
    "Hazardous Mat, Spill-Leak":["HazMat"],
    "Tranformer Fire":["Fire"],
    "Furnace Problem":["Rescue"],
    "Motor Vehicle Incident":["Vehicle"],
    "HazMat Reduced":["HazMat"],
    "Hang-Up, Fire":["Fire"],
    "Rescue Water":["Rescue","Marine"],
    "Medic Response Freeway":["Medical","Vehicle"],
    "Rescue Extrication":["Rescue"],
    "Mutual Aid, Medic":["Medical"],
    "Chimney Fire":["Fire"],
    "Food On The Stove Out":["Fire"],
    "Rescue Automobile":["Rescue","Vehicle"],
    "Car Fire Freeway":["Vehicle","Fire"],
    "Trans to AMR":["Medical"],
    "Investigate In Service":["Rescue"],
    "Assault w/Weapons, Aid":["Medical"],
    "Food On The Stove":["Fire"],
    "3RED - 1 +1 + 1":["Medical"],
    "Aid Response Freeway":["Medical","Vehicle"],
    "Natural Gas Leak":["HazMat"],
    "Single Medic Unit":["Medical"],
    "Dumpster Fire":["Fire"],
    "Advised Incident":["Rescue"],
    "MVI Freeway":["Vehicle"],
    "AFA4 - Auto Alarm 2 + 1 + 1":["Fire"],
    "Rescue Heavy":["Rescue"],
    "Fuel Spill":["HazMat"],
    "Wires Down":["Rescue"],
    "Electrical Problem":["Rescue"],
    "Bark Fire":["Fire"],
    "Fire in Single Family Res":["Fire"],
    "Rescue Lock In/Out":["Rescue"],
    "Rubbish Fire":["Fire"],
    "Assault w/Weap 7 per Rule":["Medical"],
    "Activated CO Detector":["HazMat"],
    "Brush Fire":["Fire"],
    "Fire in Building":["Fire"],
    "Natural Gas Odor":["HazMat"],
    "4RED - 2 + 1 + 1":["Medical"],
    "Unk Odor":["HazMat"],
    "Water Job Minor":["Rescue"],
    "Hang-Up, Aid":["Medical"],
    "Medic Response, 6 per Rule":["Medical"],
    "Illegal Burn":["Fire"],
    "Alarm Bell":["Fire"],
    "Car Fire":["Fire","Vehicle"],
    "Motor Vehicle Accident Freeway":["Vehicle"],
    "MVI - Motor Vehicle Incident":["Vehicle"],
    "Automatic Fire Alarm False":["Fire"],
    "Investigate Out Of Service":["Rescue"],
    "Rescue Elevator":["Rescue"],
    "1RED 1 Unit":["Medical"],
    "Automatic Medical Alarm":["Medical"],
    "Medic Response, 7 per Rule":["Medical"],
    "Automatic Fire Alarm Resd":["Fire"],
    "Aid Response Yellow":["Medical"],
    "Motor Vehicle Accident":["Vehicle"],
    "Auto Fire Alarm":["Fire"],
    "Medic Response":["Medical"],
    "Aid Response":["Medical"]
    }
    return types

