def allunits():
    units = {
    'A10':'Aid Car',
    'A14':'Aid Car',
    'A5':'Aid Car',
    'A25':'Aid Car',
    'A2':'Aid Car',
    'AIR240':'Air Supply',
    'AIR260':'Air Supply',
    'AIR9':'Air Supply',
    'B22':'Battalion Chief',
    'B7':'Battalion Chief',
    'B4':'Battalion Chief',
    'B2':'Battalion Chief',
    'B6':'Battalion Chief',
    'B5':'Battalion Chief',
    'CHAP7':'Chaplain',
    'CHAP3':'Chaplain',
    'CHAP6':'Chaplain',
    'CHAP5':'Chaplain',
    'DECON1':'Decontamination',
    'DEP1':'Deputy Chief',
    'E41':'Engine',
    'E36':'Engine',
    'E26':'Engine',
    'E34':'Engine',
    'E27':'Engine',
    'E20':'Engine',
    'E22':'Engine',
    'E29':'Engine',
    'E40':'Engine',
    'E35':'Engine',
    'E8':'Engine',
    'E21':'Engine',
    'E38':'Engine',
    'E32':'Engine',
    'E9':'Engine',
    'E16':'Engine',
    'E13':'Engine',
    'E11':'Engine',
    'E30':'Engine',
    'E37':'Engine',
    'E33':'Engine',
    'E18':'Engine',
    'E6':'Engine',
    'E24':'Engine',
    'E39':'Engine',
    'E10':'Engine',
    'E5':'Engine',
    'E25':'Engine',
    'E17':'Engine',
    'E2':'Engine',
    'E28':'Engine',
    'E31':'Engine',
    'MAR31':'Fire Marshal',
    'MAR51':'Fire Marshal',
    'MAR5':'Fire Marshal',
    'FB4':'Fireboat',
    'FIREBOAT':'Fireboat',
    'HAZVAN':'HazMat',
    'HAZ1':'HazMat',
    'L6':'Ladder',
    'L11':'Ladder',
    'L7':'Ladder',
    'L8':'Ladder',
    'L3':'Ladder',
    'L12':'Ladder',
    'L1':'Ladder',
    'L9':'Ladder',
    'L10':'Ladder',
    'L5':'Ladder',
    'L4':'Ladder',
    'MCI1':'Mass Casualty',
    'M18':'Medic',
    'M32':'Medic',
    'M28':'Medic',
    'M31':'Medic',
    'M16':'Medic',
    'M10':'Medic',
    'M1':'Medic',
    'M80':'Medic (Reserve)',
    'M45':'Medic Supervisor',
    'M44':'Medic Supervisor',
    'PIO':'Public Information Officer',
    'REHAB1':'Rehab',
    'R1':'Rescue',
    'SAFT2':'Safety Chief',
    'STAF10':'Staff Support Unit',
    'MVU1':'Ventilation'
    }
    return units
