from collections import OrderedDict

def allunits():
    units = OrderedDict([
    ('A10',{'location':'Pioneer Square','type':'Aid Car'}),
    ('A14',{'location':'SoDo','type':'Aid Car'}),
    ('A5',{'location':'Pioneer Square','type':'Aid Car'}),
    ('A4',{'location':'Belltown','type':'Aid Car'}),
    ('A25',{'location':'Capitol Hill','type':'Aid Car'}),
    ('A2',{'location':'Belltown','type':'Aid Car'}),
    ('A82',{'location':'(Reserve)','type':'Aid Car'}),
    ('A83',{'location':'(Reserve)','type':'Aid Car'}),
    ('A84',{'location':'(Reserve)','type':'Aid Car'}),
    ('A85',{'location':'(Reserve)','type':'Aid Car'}),
    ('A86',{'location':'(Reserve)','type':'Aid Car'}),
    ('A87',{'location':'(Reserve)','type':'Aid Car'}),
    ('AIR240',{'location':'Bitter Lake','type':'Air Supply'}),
    ('AIR260',{'location':'South Park','type':'Air Supply'}),
    ('AIR9',{'location':'Mount Baker','type':'Air Supply'}),
    ('B22',{'location':'Capitol Hill','type':'Battalion Chief'}),
    ('B7',{'location':'West Seattle','type':'Battalion Chief'}),
    ('B4',{'location':'Ballard','type':'Battalion Chief'}),
    ('B2',{'location':'Capitol Hill','type':'Battalion Chief'}),
    ('B6',{'location':'University District','type':'Battalion Chief'}),
    ('B5',{'location':'Beacon Hill','type':'Battalion Chief'}),
    ('CHAP7',{'location':'(Reserve)','type':'Chaplain'}),
    ('CHAP3',{'location':'(Reserve)','type':'Chaplain'}),
    ('CHAP6',{'location':'(Reserve)','type':'Chaplain'}),
    ('CHAP5',{'location':'(Reserve)','type':'Chaplain'}),
    ('DECON1',{'location':'Georgetown','type':'Decontamination'}),
    ('DEP1',{'location':'Pioneer Square','type':'Deputy Chief'}),
    ('E41',{'location':'Magnolia','type':'Engine'}),
    ('E36',{'location':'Harbor Island','type':'Engine'}),
    ('E26',{'location':'South Park','type':'Engine'}),
    ('E34',{'location':'Madison Park','type':'Engine'}),
    ('E27',{'location':'Georgetown','type':'Engine'}),
    ('E20',{'location':'Interbay','type':'Engine'}),
    ('E22',{'location':'Montlake','type':'Engine'}),
    ('E29',{'location':'Admiral District','type':'Engine'}),
    ('E40',{'location':'Wedgwood','type':'Engine'}),
    ('E35',{'location':'Crown Hill','type':'Engine'}),
    ('E8',{'location':'Queen Anne','type':'Engine'}),
    ('E21',{'location':'Greenwood','type':'Engine'}),
    ('E38',{'location':'Laurelhurst','type':'Engine'}),
    ('E32',{'location':'West Seattle','type':'Engine'}),
    ('E9',{'location':'Fremont','type':'Engine'}),
    ('E16',{'location':'Greenlake','type':'Engine'}),
    ('E13',{'location':'Beacon Hill','type':'Engine'}),
    ('E11',{'location':'Highland Park','type':'Engine'}),
    ('E30',{'location':'Mount Baker','type':'Engine'}),
    ('E37',{'location':'High Point','type':'Engine'}),
    ('E33',{'location':'Rainier Beach','type':'Engine'}),
    ('E18',{'location':'Ballard','type':'Engine'}),
    ('E6',{'location':'Central District','type':'Engine'}),
    ('E24',{'location':'Bitter Lake','type':'Engine'}),
    ('E39',{'location':'Lake City','type':'Engine'}),
    ('E10',{'location':'Pioneer Square','type':'Engine'}),
    ('E5',{'location':'Belltown','type':'Engine'}),
    ('E25',{'location':'Capitol Hill','type':'Engine'}),
    ('E17',{'location':'University District','type':'Engine'}),
    ('E2',{'location':'Belltown','type':'Engine'}),
    ('E28',{'location':'Rainier Valley','type':'Engine'}),
    ('E31',{'location':'Northgate','type':'Engine'}),
    ('MAR31',{'location':'Headquarters','type':'Fire Marshal'}),
    ('MAR51',{'location':'Headquarters','type':'Fire Marshal'}),
    ('MAR5',{'location':'Headquarters','type':'Fire Marshal'}),
    ('MRN1',{'location':'Harbor Island','type':'Marine'}),
    ('FB1',{'location':'Fishermen\'s Terminal','type':'Fireboat'}),
    ('FB2',{'location':'Waterfront','type':'Fireboat'}),
    ('FB3',{'location':'Fishermen\'s Terminal','type':'Fireboat'}),
    ('FB4',{'location':'Waterfront','type':'Fireboat'}),
    ('FRB4',{'location':'Waterfront','type':'Fire Rescue Boat'}),
    ('FIREBOAT',{'location':'Waterfront','type':'Fireboat'}),
    ('HAZVAN',{'location':'Pioneer Square','type':'HazMat'}),
    ('HAZ1',{'location':'Pioneer Square','type':'HazMat'}),
    ('L6',{'location':'Queen Anne','type':'Ladder'}),
    ('L11',{'location':'West Seattle','type':'Ladder'}),
    ('L13',{'location':'Highland Park','type':'Ladder'}),
    ('L7',{'location':'SoDo','type':'Ladder'}),
    ('L8',{'location':'Ballard','type':'Ladder'}),
    ('L3',{'location':'Central District','type':'Ladder'}),
    ('L12',{'location':'Rainier Valley','type':'Ladder'}),
    ('L1',{'location':'Pioneer Square','type':'Ladder'}),
    ('L9',{'location':'University District','type':'Ladder'}),
    ('L10',{'location':'Capitol Hill','type':'Ladder'}),
    ('L5',{'location':'Northgate','type':'Ladder'}),
    ('L4',{'location':'Belltown','type':'Ladder'}),
    ('MCI1',{'location':'Greenwood','type':'Mass Casualty'}),
    ('M18',{'location':'Ballard','type':'Medic'}),
    ('M32',{'location':'High Point','type':'Medic'}),
    ('M28',{'location':'Rainier Valley','type':'Medic'}),
    ('M31',{'location':'Northgate','type':'Medic'}),
    ('M16',{'location':'University District','type':'Medic'}),
    ('M10',{'location':'Harborview','type':'Medic'}),
    ('M1',{'location':'Harborview','type':'Medic'}),
    ('M80',{'location':'(Reserve)','type':'Medic'}),
    ('M45',{'location':'Harborview','type':'Medic Battalion Chief'}),
    ('M44',{'location':'Harborview','type':'Medic Supervisor'}),
    ('PIO',{'location':'Headquarters','type':'Public Information Officer'}),
    ('REHAB1',{'location':'Georgetown','type':'Rehab'}),
    ('R1',{'location':'SoDo','type':'Rescue'}),
    ('SAFT2',{'location':'Headquarters','type':'Safety Chief'}),
    ('STAF10',{'location':'Pioneer Square','type':'Staff Support Unit'}),
    ('MVU1',{'location':'Capitol Hill','type':'Ventilation'}),
    ('COMVAN',{'location':'Montlake','type':'Command Van'})
    ])
    return units
